/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetFwLeaderboardsCorporationsKills : Top 10 rankings of corporations by number of kills from yesterday, last week and in total



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetFwLeaderboardsCorporationsKills {
    /// Top 10 ranking of corporations active in faction warfare by total kills. A corporation is considered \"active\" if they have participated in faction warfare in the past 14 days
    #[serde(rename = "active_total")]
    pub active_total: Vec<crate::models::GetFwLeaderboardsCorporationsActiveTotalActiveTotal>,
    /// Top 10 ranking of corporations by kills in the past week
    #[serde(rename = "last_week")]
    pub last_week: Vec<crate::models::GetFwLeaderboardsCorporationsLastWeekLastWeek>,
    /// Top 10 ranking of corporations by kills in the past day
    #[serde(rename = "yesterday")]
    pub yesterday: Vec<crate::models::GetFwLeaderboardsCorporationsYesterdayYesterday>,
}

impl GetFwLeaderboardsCorporationsKills {
    /// Top 10 rankings of corporations by number of kills from yesterday, last week and in total
    pub fn new(active_total: Vec<crate::models::GetFwLeaderboardsCorporationsActiveTotalActiveTotal>, last_week: Vec<crate::models::GetFwLeaderboardsCorporationsLastWeekLastWeek>, yesterday: Vec<crate::models::GetFwLeaderboardsCorporationsYesterdayYesterday>) -> GetFwLeaderboardsCorporationsKills {
        GetFwLeaderboardsCorporationsKills {
            active_total,
            last_week,
            yesterday,
        }
    }
}


