/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetCharactersCharacterIdPlanetsPlanetIdLink : link object



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetCharactersCharacterIdPlanetsPlanetIdLink {
    /// destination_pin_id integer
    #[serde(rename = "destination_pin_id")]
    pub destination_pin_id: i64,
    /// link_level integer
    #[serde(rename = "link_level")]
    pub link_level: i32,
    /// source_pin_id integer
    #[serde(rename = "source_pin_id")]
    pub source_pin_id: i64,
}

impl GetCharactersCharacterIdPlanetsPlanetIdLink {
    /// link object
    pub fn new(destination_pin_id: i64, link_level: i32, source_pin_id: i64) -> GetCharactersCharacterIdPlanetsPlanetIdLink {
        GetCharactersCharacterIdPlanetsPlanetIdLink {
            destination_pin_id,
            link_level,
            source_pin_id,
        }
    }
}


