/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetFleetsFleetIdWings200Ok : 200 ok object



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetFleetsFleetIdWings200Ok {
    /// id integer
    #[serde(rename = "id")]
    pub id: i64,
    /// name string
    #[serde(rename = "name")]
    pub name: String,
    /// squads array
    #[serde(rename = "squads")]
    pub squads: Vec<crate::models::GetFleetsFleetIdWingsSquad>,
}

impl GetFleetsFleetIdWings200Ok {
    /// 200 ok object
    pub fn new(id: i64, name: String, squads: Vec<crate::models::GetFleetsFleetIdWingsSquad>) -> GetFleetsFleetIdWings200Ok {
        GetFleetsFleetIdWings200Ok {
            id,
            name,
            squads,
        }
    }
}


