/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetIndustryFacilities200Ok : 200 ok object



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetIndustryFacilities200Ok {
    /// ID of the facility
    #[serde(rename = "facility_id")]
    pub facility_id: i64,
    /// Owner of the facility
    #[serde(rename = "owner_id")]
    pub owner_id: i32,
    /// Region ID where the facility is
    #[serde(rename = "region_id")]
    pub region_id: i32,
    /// Solar system ID where the facility is
    #[serde(rename = "solar_system_id")]
    pub solar_system_id: i32,
    /// Tax imposed by the facility
    #[serde(rename = "tax", skip_serializing_if = "Option::is_none")]
    pub tax: Option<f32>,
    /// Type ID of the facility
    #[serde(rename = "type_id")]
    pub type_id: i32,
}

impl GetIndustryFacilities200Ok {
    /// 200 ok object
    pub fn new(facility_id: i64, owner_id: i32, region_id: i32, solar_system_id: i32, type_id: i32) -> GetIndustryFacilities200Ok {
        GetIndustryFacilities200Ok {
            facility_id,
            owner_id,
            region_id,
            solar_system_id,
            tax: None,
            type_id,
        }
    }
}


