/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetCorporationsCorporationIdContractsContractIdBids200Ok : 200 ok object



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetCorporationsCorporationIdContractsContractIdBids200Ok {
    /// The amount bid, in ISK
    #[serde(rename = "amount")]
    pub amount: f32,
    /// Unique ID for the bid
    #[serde(rename = "bid_id")]
    pub bid_id: i32,
    /// Character ID of the bidder
    #[serde(rename = "bidder_id")]
    pub bidder_id: i32,
    /// Datetime when the bid was placed
    #[serde(rename = "date_bid")]
    pub date_bid: String,
}

impl GetCorporationsCorporationIdContractsContractIdBids200Ok {
    /// 200 ok object
    pub fn new(amount: f32, bid_id: i32, bidder_id: i32, date_bid: String) -> GetCorporationsCorporationIdContractsContractIdBids200Ok {
        GetCorporationsCorporationIdContractsContractIdBids200Ok {
            amount,
            bid_id,
            bidder_id,
            date_bid,
        }
    }
}


