/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetUniverseStructuresStructureIdOk : 200 ok object



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetUniverseStructuresStructureIdOk {
    /// The full name of the structure
    #[serde(rename = "name")]
    pub name: String,
    /// The ID of the corporation who owns this particular structure
    #[serde(rename = "owner_id")]
    pub owner_id: i32,
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<Box<crate::models::GetUniverseStructuresStructureIdPosition>>,
    /// solar_system_id integer
    #[serde(rename = "solar_system_id")]
    pub solar_system_id: i32,
    /// type_id integer
    #[serde(rename = "type_id", skip_serializing_if = "Option::is_none")]
    pub type_id: Option<i32>,
}

impl GetUniverseStructuresStructureIdOk {
    /// 200 ok object
    pub fn new(name: String, owner_id: i32, solar_system_id: i32) -> GetUniverseStructuresStructureIdOk {
        GetUniverseStructuresStructureIdOk {
            name,
            owner_id,
            position: None,
            solar_system_id,
            type_id: None,
        }
    }
}


