/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetUniverseStructuresStructureIdPosition : Coordinates of the structure in Cartesian space relative to the Sun, in metres. 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetUniverseStructuresStructureIdPosition {
    /// x number
    #[serde(rename = "x")]
    pub x: f64,
    /// y number
    #[serde(rename = "y")]
    pub y: f64,
    /// z number
    #[serde(rename = "z")]
    pub z: f64,
}

impl GetUniverseStructuresStructureIdPosition {
    /// Coordinates of the structure in Cartesian space relative to the Sun, in metres. 
    pub fn new(x: f64, y: f64, z: f64) -> GetUniverseStructuresStructureIdPosition {
        GetUniverseStructuresStructureIdPosition {
            x,
            y,
            z,
        }
    }
}


