/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetCharactersCharacterIdSkillqueue200Ok : 200 ok object



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetCharactersCharacterIdSkillqueue200Ok {
    /// Date on which training of the skill will complete. Omitted if the skill queue is paused.
    #[serde(rename = "finish_date", skip_serializing_if = "Option::is_none")]
    pub finish_date: Option<String>,
    /// finished_level integer
    #[serde(rename = "finished_level")]
    pub finished_level: i32,
    /// level_end_sp integer
    #[serde(rename = "level_end_sp", skip_serializing_if = "Option::is_none")]
    pub level_end_sp: Option<i32>,
    /// Amount of SP that was in the skill when it started training it's current level. Used to calculate % of current level complete.
    #[serde(rename = "level_start_sp", skip_serializing_if = "Option::is_none")]
    pub level_start_sp: Option<i32>,
    /// queue_position integer
    #[serde(rename = "queue_position")]
    pub queue_position: i32,
    /// skill_id integer
    #[serde(rename = "skill_id")]
    pub skill_id: i32,
    /// start_date string
    #[serde(rename = "start_date", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    /// training_start_sp integer
    #[serde(rename = "training_start_sp", skip_serializing_if = "Option::is_none")]
    pub training_start_sp: Option<i32>,
}

impl GetCharactersCharacterIdSkillqueue200Ok {
    /// 200 ok object
    pub fn new(finished_level: i32, queue_position: i32, skill_id: i32) -> GetCharactersCharacterIdSkillqueue200Ok {
        GetCharactersCharacterIdSkillqueue200Ok {
            finish_date: None,
            finished_level,
            level_end_sp: None,
            level_start_sp: None,
            queue_position,
            skill_id,
            start_date: None,
            training_start_sp: None,
        }
    }
}


