/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetCharactersCharacterIdPlanetsPlanetIdOk : 200 ok object



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetCharactersCharacterIdPlanetsPlanetIdOk {
    /// links array
    #[serde(rename = "links")]
    pub links: Vec<crate::models::GetCharactersCharacterIdPlanetsPlanetIdLink>,
    /// pins array
    #[serde(rename = "pins")]
    pub pins: Vec<crate::models::GetCharactersCharacterIdPlanetsPlanetIdPin>,
    /// routes array
    #[serde(rename = "routes")]
    pub routes: Vec<crate::models::GetCharactersCharacterIdPlanetsPlanetIdRoute>,
}

impl GetCharactersCharacterIdPlanetsPlanetIdOk {
    /// 200 ok object
    pub fn new(links: Vec<crate::models::GetCharactersCharacterIdPlanetsPlanetIdLink>, pins: Vec<crate::models::GetCharactersCharacterIdPlanetsPlanetIdPin>, routes: Vec<crate::models::GetCharactersCharacterIdPlanetsPlanetIdRoute>) -> GetCharactersCharacterIdPlanetsPlanetIdOk {
        GetCharactersCharacterIdPlanetsPlanetIdOk {
            links,
            pins,
            routes,
        }
    }
}


