/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetCharactersCharacterIdShipOk : 200 ok object



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetCharactersCharacterIdShipOk {
    /// Item id's are unique to a ship and persist until it is repackaged. This value can be used to track repeated uses of a ship, or detect when a pilot changes into a different instance of the same ship type.
    #[serde(rename = "ship_item_id")]
    pub ship_item_id: i64,
    /// ship_name string
    #[serde(rename = "ship_name")]
    pub ship_name: String,
    /// ship_type_id integer
    #[serde(rename = "ship_type_id")]
    pub ship_type_id: i32,
}

impl GetCharactersCharacterIdShipOk {
    /// 200 ok object
    pub fn new(ship_item_id: i64, ship_name: String, ship_type_id: i32) -> GetCharactersCharacterIdShipOk {
        GetCharactersCharacterIdShipOk {
            ship_item_id,
            ship_name,
            ship_type_id,
        }
    }
}


