/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetInsurancePrices200Ok : 200 ok object



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetInsurancePrices200Ok {
    /// A list of a available insurance levels for this ship type
    #[serde(rename = "levels")]
    pub levels: Vec<crate::models::GetInsurancePricesLevel>,
    /// type_id integer
    #[serde(rename = "type_id")]
    pub type_id: i32,
}

impl GetInsurancePrices200Ok {
    /// 200 ok object
    pub fn new(levels: Vec<crate::models::GetInsurancePricesLevel>, type_id: i32) -> GetInsurancePrices200Ok {
        GetInsurancePrices200Ok {
            levels,
            type_id,
        }
    }
}


