/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetFwLeaderboardsLastWeekLastWeek1 : last_week object



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetFwLeaderboardsLastWeekLastWeek1 {
    /// Amount of victory points
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<i32>,
    /// faction_id integer
    #[serde(rename = "faction_id", skip_serializing_if = "Option::is_none")]
    pub faction_id: Option<i32>,
}

impl GetFwLeaderboardsLastWeekLastWeek1 {
    /// last_week object
    pub fn new() -> GetFwLeaderboardsLastWeekLastWeek1 {
        GetFwLeaderboardsLastWeekLastWeek1 {
            amount: None,
            faction_id: None,
        }
    }
}


