/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetCharactersCharacterIdCalendarEventIdAttendees200Ok : character_id and response of an attendee



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetCharactersCharacterIdCalendarEventIdAttendees200Ok {
    /// character_id integer
    #[serde(rename = "character_id", skip_serializing_if = "Option::is_none")]
    pub character_id: Option<i32>,
    /// event_response string
    #[serde(rename = "event_response", skip_serializing_if = "Option::is_none")]
    pub event_response: Option<EventResponse>,
}

impl GetCharactersCharacterIdCalendarEventIdAttendees200Ok {
    /// character_id and response of an attendee
    pub fn new() -> GetCharactersCharacterIdCalendarEventIdAttendees200Ok {
        GetCharactersCharacterIdCalendarEventIdAttendees200Ok {
            character_id: None,
            event_response: None,
        }
    }
}

/// event_response string
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventResponse {
    #[serde(rename = "declined")]
    Declined,
    #[serde(rename = "not_responded")]
    NotResponded,
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "tentative")]
    Tentative,
}

impl Default for EventResponse {
    fn default() -> EventResponse {
        Self::Declined
    }
}

