/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetCharactersCharacterIdPortraitNotFound : No image server for this datasource



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetCharactersCharacterIdPortraitNotFound {
    /// error message
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl GetCharactersCharacterIdPortraitNotFound {
    /// No image server for this datasource
    pub fn new() -> GetCharactersCharacterIdPortraitNotFound {
        GetCharactersCharacterIdPortraitNotFound {
            error: None,
        }
    }
}


