/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetCharactersCharacterIdClonesOk : 200 ok object



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetCharactersCharacterIdClonesOk {
    #[serde(rename = "home_location", skip_serializing_if = "Option::is_none")]
    pub home_location: Option<Box<crate::models::GetCharactersCharacterIdClonesHomeLocation>>,
    /// jump_clones array
    #[serde(rename = "jump_clones")]
    pub jump_clones: Vec<crate::models::GetCharactersCharacterIdClonesJumpClone>,
    /// last_clone_jump_date string
    #[serde(rename = "last_clone_jump_date", skip_serializing_if = "Option::is_none")]
    pub last_clone_jump_date: Option<String>,
    /// last_station_change_date string
    #[serde(rename = "last_station_change_date", skip_serializing_if = "Option::is_none")]
    pub last_station_change_date: Option<String>,
}

impl GetCharactersCharacterIdClonesOk {
    /// 200 ok object
    pub fn new(jump_clones: Vec<crate::models::GetCharactersCharacterIdClonesJumpClone>) -> GetCharactersCharacterIdClonesOk {
        GetCharactersCharacterIdClonesOk {
            home_location: None,
            jump_clones,
            last_clone_jump_date: None,
            last_station_change_date: None,
        }
    }
}


