/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetWarsWarIdKillmails200Ok : 200 ok object



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetWarsWarIdKillmails200Ok {
    /// A hash of this killmail
    #[serde(rename = "killmail_hash")]
    pub killmail_hash: String,
    /// ID of this killmail
    #[serde(rename = "killmail_id")]
    pub killmail_id: i32,
}

impl GetWarsWarIdKillmails200Ok {
    /// 200 ok object
    pub fn new(killmail_hash: String, killmail_id: i32) -> GetWarsWarIdKillmails200Ok {
        GetWarsWarIdKillmails200Ok {
            killmail_hash,
            killmail_id,
        }
    }
}


