/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetCharactersCharacterIdBookmarksCoordinates : Optional object that is returned if a bookmark was made on a planet or a random location in space.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetCharactersCharacterIdBookmarksCoordinates {
    /// x number
    #[serde(rename = "x")]
    pub x: f64,
    /// y number
    #[serde(rename = "y")]
    pub y: f64,
    /// z number
    #[serde(rename = "z")]
    pub z: f64,
}

impl GetCharactersCharacterIdBookmarksCoordinates {
    /// Optional object that is returned if a bookmark was made on a planet or a random location in space.
    pub fn new(x: f64, y: f64, z: f64) -> GetCharactersCharacterIdBookmarksCoordinates {
        GetCharactersCharacterIdBookmarksCoordinates {
            x,
            y,
            z,
        }
    }
}


