/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PostCharactersCharacterIdFittingsCreated : 201 created object



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostCharactersCharacterIdFittingsCreated {
    /// fitting_id integer
    #[serde(rename = "fitting_id")]
    pub fitting_id: i32,
}

impl PostCharactersCharacterIdFittingsCreated {
    /// 201 created object
    pub fn new(fitting_id: i32) -> PostCharactersCharacterIdFittingsCreated {
        PostCharactersCharacterIdFittingsCreated {
            fitting_id,
        }
    }
}


